[phases.setup]
nixPkgs = ["nodejs", "npm"]

[build]
builder = "DOCKERFILE"
dockerfilePath = "frontend/Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
VITE_API_URL = "https://rpg-session-organizer-staging.up.railway.app" 