[phases.setup]
nixPkgs = ["nodejs", "npm"]

[build]
builder = "DOCKERFILE"
dockerfilePath = "frontend/Dockerfile"
buildContext = "frontend"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 