version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - RAILS_MAX_THREADS=5
      - RAILS_LOG_LEVEL=debug
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:create db:migrate &&
        bundle exec rails server -b '0.0.0.0'
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  bundle_cache:
  node_modules: 