[phases.setup]
nixPkgs = ["ruby", "bundler"]

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "entrypoint.sh"
# Temporarily disabled healthcheck for debugging
# healthcheckPath = "/api/health"
# healthcheckTimeout = 100

[deploy.services]
backend = { path = "backend" }
frontend = { path = "frontend" } 