[phases.setup]
nixPkgs = ["ruby", "bundler"]

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bundle exec rails server -b 0.0.0.0 -p ${PORT:-8080}"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[deploy.services]
backend = { path = "backend" }
frontend = { path = "frontend" } 