[phases.setup]
nixPkgs = ["ruby", "bundler"]

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "entrypoint.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[deploy.services]
backend = { path = "backend" }
frontend = { path = "frontend" } 