[build]
builder = "nixpacks"
buildCommand = "echo 'No build command needed for monorepo'"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.services]
backend = { 
  path = "backend",
  startCommand = "bundle exec rails server -b 0.0.0.0"
}
frontend = { 
  path = "frontend",
  startCommand = "npm run preview"
} 