[phases.setup]
nixPkgs = ["ruby", "bundler"]

[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
buildContext = "backend"
watchPaths = ["backend/**/*"]

[deploy]
startCommand = "entrypoint.sh"

restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 